rootProject.name = 'gavel'

include 'gavel-domain'
include 'gavel-application'
include 'gavel-backend'
include 'gavel-static-analysis'

include 'gavel-git-adapter'
include 'gavel-language-adapter-generic'
include 'gavel-language-adapter-java'
include 'gavel-owasp-dependency-check-adapter'
include 'gavel-persistence-adapter'
include 'gavel-pmd-adapter'
include 'gavel-spotbugs-adapter'