dependencies {
    api project(':gavel-domain')
    implementation "net.sourceforge.pmd:pmd-core:7.27.0"
    //TODO: Move java dependency and maybe provide means for other language implementations to be used as well
    implementation "net.sourceforge.pmd:pmd-java:7.27.0"
    implementation("io.github.classgraph:classgraph:4.8.181")
}