import {Observable, of} from "rxjs";
import {randomizedDelay} from "../../util/fakes";
import {Injectable} from "@angular/core";

export class CodeHotspot {
  constructor(public fileName: string,
              public numberOfChanges: number) {
  }
}

@Injectable({
  providedIn: 'root'
})
export default class CodeHotspotMetricsService {

  private metrics: CodeHotspot[] = [{
    "fileName": "boundary-acceptance-test/src/integrationTest/java/pendenzenliste/boundary/cucumber/ToDoSteps.java",
    "numberOfChanges": 3
  }, {
    "fileName": "gateway-eclipse-store/src/main/java/pendenzenliste/achievements/gateway/eclipsestore/EclipseStoreAchievementGateway.java",
    "numberOfChanges": 2
  }, {
    "fileName": "boundary/src/main/java/pendenzenliste/todos/boundary/out/ToDoOutputBoundaryFactory.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/ToDoEntity.java",
    "numberOfChanges": 3
  }, {
    "fileName": "domain-achievements/src/test/java/pendenzenliste/achievements/model/AchievementFactoryTest.java",
    "numberOfChanges": 1
  }, {
    "fileName": "boundary/src/main/java/pendenzenliste/todos/boundary/in/PurgeOldToDosRequest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-achievements/src/test/java/pendenzenliste/achievements/model/AchievementProgressTrackingServiceTest.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-discord-bot/src/main/java/pendenzenliste/discord4j/ToDoPresenterFactory.java",
    "numberOfChanges": 2
  }, {
    "fileName": "boundary-usecases/src/main/java/pendenzenliste/todos/usecases/DeleteToDoUseCase.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-vaadin/src/main/java/pendenzenliste/vaadin/AchievementTranslationUtils.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-discord-bot/src/main/java/pendenzenliste/discord4j/DiscordBot.java",
    "numberOfChanges": 1
  }, {
    "fileName": "boundary-acceptance-test/src/integrationTest/java/pendenzenliste/boundary/cucumber/CapturingOutputBoundaryFactory.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-postgresql-jooq/src/main/java/pendenzenliste/gateway/postgresql/PostgreSQLAchievementGateway.java",
    "numberOfChanges": 3
  }, {
    "fileName": "gateway-eclipse-store/src/main/java/module-info.java",
    "numberOfChanges": 2
  }, {
    "fileName": "boundary-acceptance-test/src/main/java/pendenzenliste/acceptancetests/ToolVersion.java",
    "numberOfChanges": 1
  }, {
    "fileName": "vaadin-binding-properties/src/test/java/pendenzenliste/vaadin/binding/BooleanBindingPropertyTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "util-domain/src/main/java/pendenzenliste/domain/util/Entity.java",
    "numberOfChanges": 1
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/CompletedTimestampValueObject.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-redis/src/main/java/pendenzenliste/gateway/redis/RedisAchievementGateway.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-dropwizard/src/main/java/pendenzenliste/dropwizard/JsonCreateToDoPresenter.java",
    "numberOfChanges": 3
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/ToDoAggregate.java",
    "numberOfChanges": 7
  }, {
    "fileName": "boundary-usecases/src/main/java/pendenzenliste/todos/usecases/PurgeOldToDosUseCase.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/main/java/pendenzenliste/cli/CommandLineResult.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-vaadin/src/test/java/pendenzenliste/vaadin/FetchAchievementListPresenterTest.java",
    "numberOfChanges": 4
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/ToDoService.java",
    "numberOfChanges": 1
  }, {
    "fileName": "boundary-acceptance-test/src/main/java/pendenzenliste/acceptancetests/VersionParser.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-javafx/src/main/java/pendenzenliste/javafx/ToDoPresenterFactory.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/CompleteToDoCommand.java",
    "numberOfChanges": 1
  }, {
    "fileName": "domain-todos/src/test/java/pendenzenliste/todos/model/ToDoAggregateTest.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-javafx/src/main/java/pendenzenliste/javafx/FetchToDoListPresenter.java",
    "numberOfChanges": 1
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/UpdateToDoCommand.java",
    "numberOfChanges": 1
  }, {
    "fileName": "gateway-eclipse-store/src/main/java/pendenzenliste/todos/gateway/eclipsestore/EclipseStoreToDoGatewayProvider.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/main/java/pendenzenliste/cli/ToDoPresenterFactory.java",
    "numberOfChanges": 6
  }, {
    "fileName": "boundary-usecases/src/main/java/pendenzenliste/todos/usecases/CreateToDoUseCase.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-vaadin/src/test/java/pendenzenliste/vaadin/StateBadgeWidgetTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/main/java/pendenzenliste/cli/FetchToDoListPresenter.java",
    "numberOfChanges": 3
  }, {
    "fileName": "domain-todos/src/main/java/module-info.java",
    "numberOfChanges": 1
  }, {
    "fileName": "util-domain/src/main/java/module-info.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-vaadin/src/test/java/pendenzenliste/vaadin/ToDoControllerTest.java",
    "numberOfChanges": 3
  }, {
    "fileName": "gateway-postgresql-jooq/src/main/java/pendenzenliste/gateway/postgresql/PostgreSQLToDoGateway.java",
    "numberOfChanges": 4
  }, {
    "fileName": "boundary-usecases/src/main/java/pendenzenliste/todos/usecases/ToDoUseCaseFactory.java",
    "numberOfChanges": 3
  }, {
    "fileName": "boundary/src/main/java/pendenzenliste/todos/boundary/in/PurgeOldToDosInputBoundary.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-achievements/src/main/java/pendenzenliste/achievements/model/AchievementRepository.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-dropwizard/src/main/java/pendenzenliste/dropwizard/JsonToDoPresenterFactory.java",
    "numberOfChanges": 6
  }, {
    "fileName": "app-dropwizard/src/main/java/pendenzenliste/dropwizard/ToDoController.java",
    "numberOfChanges": 5
  }, {
    "fileName": "gateway/src/main/java/pendenzenliste/achievements/gateway/AchievementEventTrackingSubscriber.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-achievements/src/main/java/pendenzenliste/achievements/model/AbstractAchievementAggregate.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-achievements/src/test/java/pendenzenliste/achievements/model/AchievementEventEntityTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-dropwizard/src/main/java/pendenzenliste/dropwizard/JsonUpdateToDoPresenter.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-filesystem/src/main/java/pendenzenliste/achievements/gateway/filesystem/FilesystemAchievementGatewayProvider.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-dropwizard/src/main/java/pendenzenliste/dropwizard/JsonCreateToDoData.java",
    "numberOfChanges": 4
  }, {
    "fileName": "app-dropwizard/src/test/java/pendenzenliste/dropwizard/ToDoControllerTest.java",
    "numberOfChanges": 3
  }, {
    "fileName": "boundary/src/main/java/pendenzenliste/todos/boundary/out/PurgeToDoOutputBoundary.java",
    "numberOfChanges": 2
  }, {
    "fileName": "boundary/src/main/java/pendenzenliste/todos/boundary/out/PurgedToDosResponse.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/test/java/pendenzenliste/cli/UpdateToDoPresenterTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-eclipse-store/src/main/java/pendenzenliste/todos/gateway/eclipsestore/ToDoStore.java",
    "numberOfChanges": 2
  }, {
    "fileName": "boundary-acceptance-test/src/integrationTest/java/pendenzenliste/boundary/cucumber/ToDoGatewayFactory.java",
    "numberOfChanges": 3
  }, {
    "fileName": "vaadin-binding-properties/src/test/java/pendenzenliste/vaadin/binding/StringBindingPropertyTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "util-domain/src/main/java/pendenzenliste/domain/util/HasCapabilities.java",
    "numberOfChanges": 1
  }, {
    "fileName": "boundary-usecases/src/main/java/pendenzenliste/todos/usecases/ReopenToDoUseCase.java",
    "numberOfChanges": 1
  }, {
    "fileName": "gateway-eclipse-store/src/main/java/pendenzenliste/achievements/gateway/eclipsestore/AchievementsStore.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-acceptance-test/src/integrationTest/java/pendenzenliste/todos/cucumber/ToDoGatewayAcceptanceTestSteps.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-dropwizard/src/test/java/pendenzenliste/dropwizard/JsonCreateToDoPresenterTest.java",
    "numberOfChanges": 3
  }, {
    "fileName": "gateway/src/main/java/pendenzenliste/achievements/gateway/AchievementGateway.java",
    "numberOfChanges": 1
  }, {
    "fileName": "boundary-acceptance-test/src/integrationTest/java/pendenzenliste/boundary/cucumber/ToDoRequestBuilder.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/test/java/pendenzenliste/cli/FetchToDoPresenterTest.java",
    "numberOfChanges": 1
  }, {
    "fileName": "boundary/src/main/java/pendenzenliste/todos/boundary/in/ToDoInputBoundaryFactory.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/test/java/pendenzenliste/cli/FetchToDoListPresenterTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/main/java/pendenzenliste/cli/FetchToDoPresenter.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-discord-bot/src/main/java/pendenzenliste/discord4j/GlobalCommandRegistrar.java",
    "numberOfChanges": 1
  }, {
    "fileName": "gateway/src/main/java/pendenzenliste/todos/gateway/ToDoGateway.java",
    "numberOfChanges": 4
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/ToDoRepository.java",
    "numberOfChanges": 1
  }, {
    "fileName": "boundary-usecases/src/main/java/pendenzenliste/todos/usecases/UpdateToDoUseCase.java",
    "numberOfChanges": 1
  }, {
    "fileName": "vaadin-binding-properties/src/main/java/pendenzenliste/vaadin/binding/BooleanBindingProperty.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-dropwizard/src/main/java/pendenzenliste/dropwizard/ToDoResource.java",
    "numberOfChanges": 5
  }, {
    "fileName": "app-vaadin/src/main/java/pendenzenliste/vaadin/FetchAchievementListPresenter.java",
    "numberOfChanges": 3
  }, {
    "fileName": "gateway-filesystem/src/main/java/pendenzenliste/achievements/gateway/filesystem/FilesystemAchievementGateway.java",
    "numberOfChanges": 3
  }, {
    "fileName": "boundary-usecases/src/main/java/pendenzenliste/todos/usecases/CompleteToDoUseCase.java",
    "numberOfChanges": 1
  }, {
    "fileName": "vaadin-binding-properties/src/main/java/pendenzenliste/vaadin/binding/BindingProperty.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-inmemory/src/main/java/pendenzenliste/gateway/inmemory/InMemoryAchievementGateway.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-eclipse-store/src/main/java/pendenzenliste/todos/gateway/eclipsestore/EclipseStoreTodoGateway.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-todos/src/main/java/pendenzenliste/todos/model/ReopenToDoCommand.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-cli/src/main/java/pendenzenliste/cli/CreateToDoPresenter.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-achievements/src/main/java/pendenzenliste/achievements/model/AchievementProgressTrackingService.java",
    "numberOfChanges": 1
  }, {
    "fileName": "domain-achievements/src/main/java/pendenzenliste/achievements/model/AchievementFactory.java",
    "numberOfChanges": 1
  }, {
    "fileName": "domain/src/main/java/module-info.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-vaadin/vite.generated.ts",
    "numberOfChanges": 1
  }, {
    "fileName": "app-vaadin/src/main/java/pendenzenliste/vaadin/ToDoView.java",
    "numberOfChanges": 1
  }, {
    "fileName": "util-serialization/src/main/java/module-info.java",
    "numberOfChanges": 2
  }, {
    "fileName": "app-cli/src/test/java/pendenzenliste/cli/CreateToDoPresenterTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-inmemory/src/main/java/pendenzenliste/gateway/inmemory/InMemoryAchievementGatewayProvider.java",
    "numberOfChanges": 1
  }, {
    "fileName": "domain-achievements/src/main/java/pendenzenliste/achievements/model/AchievementEntity.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-vaadin/src/main/java/pendenzenliste/vaadin/SubscribeAchievementsPresenter.java",
    "numberOfChanges": 2
  }, {
    "fileName": "util-serialization/src/main/java/pendenzenliste/serialization/SerializationUtils.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-vaadin/src/main/java/pendenzenliste/vaadin/ToDoPresenterFactory.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-eclipse-store/src/main/java/pendenzenliste/achievements/gateway/eclipsestore/EclipseStoreAchievementGatewayProvider.java",
    "numberOfChanges": 2
  }, {
    "fileName": "domain-achievements/src/test/java/pendenzenliste/achievements/model/IdentityValueObjectTest.java",
    "numberOfChanges": 2
  }, {
    "fileName": "boundary/src/main/java/pendenzenliste/todos/boundary/out/PurgeToDosResponse.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-filesystem/src/main/java/pendenzenliste/todos/gateway/filesystem/FilesystemToDoGateway.java",
    "numberOfChanges": 4
  }, {
    "fileName": "gateway-inmemory/src/main/java/pendenzenliste/gateway/inmemory/InMemoryToDoGateway.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-dropwizard/src/test/java/pendenzenliste/dropwizard/ToDoResourceTest.java",
    "numberOfChanges": 3
  }, {
    "fileName": "app-cli/src/main/java/pendenzenliste/cli/UpdateToDoPresenter.java",
    "numberOfChanges": 2
  }, {
    "fileName": "gateway-redis/src/main/java/pendenzenliste/gateway/redis/RedisToDoGateway.java",
    "numberOfChanges": 3
  }, {
    "fileName": "vaadin-binding-properties/src/main/java/pendenzenliste/vaadin/binding/StringBindingProperty.java",
    "numberOfChanges": 2
  }, {
    "fileName": "boundary-acceptance-test/src/test/java/pendenzenliste/acceptancetests/VersionParserTest.java",
    "numberOfChanges": 1
  }, {
    "fileName": "app-dropwizard/src/main/java/pendenzenliste/dropwizard/JsonCreatedToDoData.java",
    "numberOfChanges": 4
  }, {
    "fileName": "gateway-filesystem/src/main/java/pendenzenliste/filesystem/util/FileStorage.java",
    "numberOfChanges": 2
  }]

  public loadMetrics(): Observable<CodeHotspot[]> {
    return of(this.metrics).pipe(randomizedDelay());
  }
}
