plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

ext {
    set('springAiVersion', "1.0.0-M2")
}

dependencies {
    implementation project(':gavel-git-adapter')
    implementation project(':gavel-static-analysis')
    implementation project(':gavel-owasp-dependency-check-adapter')
    implementation project(':gavel-persistence-adapter')
    implementation project(':gavel-pmd-adapter')
    implementation project(':gavel-spotbugs-adapter')

    implementation project(':gavel-application')
    implementation project(':gavel-domain')

    implementation group: 'net.sourceforge.pmd', name: 'pmd-core', version: '7.15.0'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    //implementation 'org.springframework.ai:spring-ai-pgvector-store-spring-boot-starter'
    //implementation 'org.springframework.ai:spring-ai-postgresml-spring-boot-starter'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.springframework.graphql:spring-graphql-test'
    testImplementation 'org.springframework.ai:spring-ai-spring-boot-testcontainers'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}