package software.bananen.gavel.reports;

/**
 * The interface for all measurement based reports that are generated by gavel.
 *
 * @param <T> The type of the reported measurements.
 */
public interface Report<T> {

    /**
     * Reports the given measurements.
     *
     * @param measurements The measurements that should be reported.
     * @throws ReportException Might be thrown in case the measurements could
     *                         not be reported
     */
    void report(T measurements) throws ReportException;
}
