import {Observable} from "rxjs";
import {Injectable} from "@angular/core";
import {HttpClient} from "@angular/common/http";

export class CumulativeComponentDependency {
  constructor(public packageName: string,
              public cumulative: number,
              public average: number,
              public relativeAverage: number,
              public normalized: number) {
  }
}

@Injectable({
  providedIn: 'root'
})
export default class CumulativeComponentDependencyMetricsService {
  protected metrics: CumulativeComponentDependency[] = [{
    "packageName": "pendenzenliste",
    "cumulative": 56,
    "average": 4.0,
    "relativeAverage": 0.2857142857142857,
    "normalized": 1.2444444444444445
  }, {
    "packageName": "pendenzenliste.boundary",
    "cumulative": 3,
    "average": 1.5,
    "relativeAverage": 0.75,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.boundary.in",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.boundary.out",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.cli",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.achievements",
    "cumulative": 8,
    "average": 2.0,
    "relativeAverage": 0.5,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.achievements.boundary",
    "cumulative": 3,
    "average": 1.5,
    "relativeAverage": 0.75,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.achievements.boundary.in",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.achievements.boundary.out",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.achievements.model",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.achievements.usecases",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.achievements.gateway",
    "cumulative": 2,
    "average": 1.0,
    "relativeAverage": 0.5,
    "normalized": 0.6666666666666666
  }, {
    "packageName": "pendenzenliste.achievements.gateway.eclipsestore",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.achievements.gateway.filesystem",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.discord4j",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.acceptancetests",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.dropwizard",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.filesystem",
    "cumulative": 1,
    "average": 1.0,
    "relativeAverage": 1.0,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.filesystem.util",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.messaging",
    "cumulative": 1,
    "average": 1.0,
    "relativeAverage": 1.0,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.messaging.inmemory",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.serialization",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.vaadin",
    "cumulative": 2,
    "average": 1.0,
    "relativeAverage": 0.5,
    "normalized": 0.6666666666666666
  }, {
    "packageName": "pendenzenliste.vaadin.mixin",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.vaadin.binding",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.domain",
    "cumulative": 1,
    "average": 1.0,
    "relativeAverage": 1.0,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.domain.util",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.todos",
    "cumulative": 8,
    "average": 2.0,
    "relativeAverage": 0.5,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.todos.boundary",
    "cumulative": 3,
    "average": 1.5,
    "relativeAverage": 0.75,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.todos.boundary.in",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.todos.boundary.out",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.todos.model",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.todos.usecases",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.todos.gateway",
    "cumulative": 2,
    "average": 1.0,
    "relativeAverage": 0.5,
    "normalized": 0.6666666666666666
  }, {
    "packageName": "pendenzenliste.todos.gateway.eclipsestore",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.todos.gateway.filesystem",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.javafx",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.gateway",
    "cumulative": 3,
    "average": 1.0,
    "relativeAverage": 0.3333333333333333,
    "normalized": 0.6
  }, {
    "packageName": "pendenzenliste.gateway.postgresql",
    "cumulative": 1,
    "average": 1.0,
    "relativeAverage": 1.0,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.gateway.postgresql.generated",
    "cumulative": 1,
    "average": 1.0,
    "relativeAverage": 1.0,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.gateway.postgresql.generated.public_",
    "cumulative": 1,
    "average": 1.0,
    "relativeAverage": 1.0,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.gateway.postgresql.generated.public_.tables",
    "cumulative": 1,
    "average": 1.0,
    "relativeAverage": 1.0,
    "normalized": 1.0
  }, {
    "packageName": "pendenzenliste.gateway.postgresql.generated.public_.tables.records",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.gateway.inmemory",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }, {
    "packageName": "pendenzenliste.gateway.redis",
    "cumulative": 0,
    "average": 0.0,
    "relativeAverage": 0.0,
    "normalized": 0.0
  }]

  constructor(private httpClient: HttpClient) {
  }

  public loadMetrics(): Observable<CumulativeComponentDependency[]> {
    //TODO: Handle errors
    return this.httpClient.get<CumulativeComponentDependency[]>("http://127.0.0.1:8080/cumulative-component-dependency-metrics");
  }
}
