spring.application.name=gavel-backend
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jooq.sql-dialect=Postgres
logging.level.org.springframework.jdbc.core=INFO
logging.level.org.springframework.jdbc.core.JdbcTemplate=INFO
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=INFO
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.hibernate=INFO
# Performance improvements
spring.jpa.open-in-view=true
spring.datasource.hikari.auto-commit=false
# Gavel specific settings
gavel.spotbugs.java-home=/home/dennis/.gradle/jdks/adoptium-17-x64-hotspot-linux/jdk-17.0.5+8/
gavel.owasp.dependencycheck.pnpm.enabled=false
gavel.owasp.dependencycheck.yarn.enabled=false
gavel.owasp.dependencycheck.data-directory=/home/dennis/.dependency-check-data/
gavel.owasp.dependencycheck.nvd-api-key=xxxx
# Actuator settings
management.endpoints.web.exposure.include=*
# graphql settings
spring.graphql.graphiql.enabled=true
spring.graphql.cors.allowed-origins=http://localhost:4200